"""Generate cirka's terminal art from docs/logo (cirka-icon.jpg, cirka-logo.jpg) -> cirka/src/art_data.rs.

A terminal cannot show the JPEGs, so each logo is reduced to a small bitmap that cirka draws with half-block
characters (one character cell = two pixels stacked, ▀ ▄ █), the way Claude Code and Grok's CLIs draw their marks:

- icon: the red brush circle, the hawk and the 式 tag. Red pixels only (the 式 is cut out of the tag).
- wordmark: "cirka" in the terminal's text colour with the red dot over the i.

Run after changing a logo:  uv run python scripts/gen_cirka_art.py [--preview artifacts/cirka-art.png]
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
LOGO_DIR = ROOT / "docs" / "logo"
OUT = ROOT / "cirka" / "src" / "art_data.rs"


def classify(rgb: tuple[int, int, int]) -> str:
    r, g, b = rgb
    if r > 150 and g < 120 and b < 120 and r - g > 60:
        return "r"  # the logo red
    if r + g + b < 300:
        return "k"  # the dark wordmark
    return "."


def bbox(img: Image.Image, keep: set[str]) -> tuple[int, int, int, int]:
    small = img.resize((img.width // 4, img.height // 4))
    xs, ys = [], []
    for y in range(small.height):
        for x in range(small.width):
            if classify(small.getpixel((x, y))) in keep:
                xs.append(x)
                ys.append(y)
    pad = 2
    return (max(0, (min(xs) - pad) * 4), max(0, (min(ys) - pad) * 4),
            min(img.width, (max(xs) + pad + 1) * 4), min(img.height, (max(ys) + pad + 1) * 4))


def bitmap(path: Path, width: int, keep: set[str], threshold: float) -> list[str]:
    """Area coverage per pixel cell: a cell takes the most covered class when it covers ``threshold``."""
    img = Image.open(path).convert("RGB")
    box = bbox(img, keep)
    img = img.crop(box)
    height = round(width * img.height / img.width)
    height += height % 2  # whole character rows
    cw, ch = img.width / width, img.height / height
    rows = []
    for gy in range(height):
        row = []
        for gx in range(width):
            counts: dict[str, int] = {}
            total = 0
            x0, y0 = int(gx * cw), int(gy * ch)
            x1, y1 = max(x0 + 1, int((gx + 1) * cw)), max(y0 + 1, int((gy + 1) * ch))
            for y in range(y0, y1, 2):
                for x in range(x0, x1, 2):
                    c = classify(img.getpixel((x, y)))
                    counts[c] = counts.get(c, 0) + 1
                    total += 1
            best = max((k for k in counts if k in keep), key=lambda k: counts[k], default=".")
            row.append(best if best != "." and counts[best] / total >= threshold else ".")
        rows.append("".join(row))
    return rows


def rust_array(name: str, rows: list[str], doc: str) -> str:
    body = "\n".join(f'    "{r}",' for r in rows)
    return f"/// {doc}\npub const {name}: &[&str] = &[\n{body}\n];\n"


def preview(path: Path, art: dict[str, list[str]]) -> None:
    """A PNG of what the terminal shows (each bitmap pixel 6×6, half blocks are square pixels)."""
    scale, gap = 6, 30
    w = sum(len(r[0]) for r in art.values()) * scale + gap * (len(art) + 1)
    h = max(len(r) for r in art.values()) * scale + 2 * gap
    img = Image.new("RGB", (w, h), (24, 24, 27))
    draw = ImageDraw.Draw(img)
    x0 = gap
    for rows in art.values():
        for y, row in enumerate(rows):
            for x, c in enumerate(row):
                if c != ".":
                    colour = (214, 58, 47) if c == "r" else (235, 235, 235)
                    draw.rectangle([x0 + x * scale, gap + y * scale, x0 + (x + 1) * scale - 1,
                                    gap + (y + 1) * scale - 1], fill=colour)
        x0 += len(rows[0]) * scale + gap
    img.save(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    icon = bitmap(LOGO_DIR / "cirka-icon.jpg", 22, {"r"}, 0.45)
    small = bitmap(LOGO_DIR / "cirka-icon.jpg", 14, {"r"}, 0.45)
    word = bitmap(LOGO_DIR / "cirka-logo.jpg", 44, {"k", "r"}, 0.30)
    word_small = bitmap(LOGO_DIR / "cirka-logo.jpg", 30, {"k", "r"}, 0.30)
    text = ("// Generated by scripts/gen_cirka_art.py from docs/logo/cirka-icon.jpg and cirka-logo.jpg. Do not edit.\n"
            "// Pixels: '.' empty, 'r' logo red, 'k' text colour. Two pixel rows make one character row.\n\n"
            + rust_array("ICON", icon, "The mark (cirka-icon.jpg): circle, hawk and the 式 tag, for tall terminals and `cirka logo`.")
            + "\n" + rust_array("ICON_SMALL", small, "The mark for the welcome box.")
            + "\n" + rust_array("WORDMARK", word, "The wordmark (cirka-logo.jpg): \"cirka\" with the red dot.")
            + "\n" + rust_array("WORDMARK_SMALL", word_small, "The wordmark for narrow terminals."))
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} (icon {len(icon[0])}x{len(icon)}, wordmark {len(word[0])}x{len(word)})")
    if args.preview:
        preview(args.preview, {"icon": icon, "small": small, "word": word, "word_small": word_small})
        print(f"preview {args.preview}")


if __name__ == "__main__":
    main()
